#!/usr/bin/env python3
"""8b/10b reference model (IEEE 802.3 clause 36) and Verilog table generator.

    python3 gen_8b10b.py        -> enc8b10b.v, dec8b10b.v, and a self-check

The encoder is written from the 5b/6b and 3b/4b sub-block tables with
running disparity carried between sub-blocks; the decoder is the exact
inverse, generated by encoding every (byte, K, RD) and inverting the map, so
the two can never disagree. The self-check verifies the properties the
standard guarantees: every code has disparity 0 or +/-2, the sign follows the
running disparity, no code has more than 5 equal bits in a row, and the comma
(0011111 / 1100000) appears only in K28.1, K28.5 and K28.7.

Bit order: the 10-bit code is 'abcdei fghj' with a in bit 9, sent first
(bit 9 first on the wire, as 1000BASE-X transmits 'a' first).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# 5b/6b: EDCBA value -> (abcdei for RD-, abcdei for RD+)
D6 = {
    0: ('100111', '011000'), 1: ('011101', '100010'), 2: ('101101', '010010'), 3: ('110001', '110001'),
    4: ('110101', '001010'), 5: ('101001', '101001'), 6: ('011001', '011001'), 7: ('111000', '000111'),
    8: ('111001', '000110'), 9: ('100101', '100101'), 10: ('010101', '010101'), 11: ('110100', '110100'),
    12: ('001101', '001101'), 13: ('101100', '101100'), 14: ('011100', '011100'), 15: ('010111', '101000'),
    16: ('011011', '100100'), 17: ('100011', '100011'), 18: ('010011', '010011'), 19: ('110010', '110010'),
    20: ('001011', '001011'), 21: ('101010', '101010'), 22: ('011010', '011010'), 23: ('111010', '000101'),
    24: ('110011', '001100'), 25: ('100110', '100110'), 26: ('010110', '010110'), 27: ('110110', '001001'),
    28: ('001110', '001110'), 29: ('101110', '010001'), 30: ('011110', '100001'), 31: ('101011', '010100'),
}
K28_6 = ('001111', '110000')
# 3b/4b: HGF value -> (fghj for RD-, fghj for RD+); 7 has the alternate A7
D4 = {0: ('1011', '0100'), 1: ('1001', '1001'), 2: ('0101', '0101'), 3: ('1100', '0011'),
      4: ('1101', '0010'), 5: ('1010', '1010'), 6: ('0110', '0110'), 7: ('1110', '0001')}
A7 = ('0111', '1000')
K_CODES = {0x1C, 0x3C, 0x5C, 0x7C, 0x9C, 0xBC, 0xDC, 0xFC,   # K28.0 .. K28.7
           0xF7, 0xFB, 0xFD, 0xFE}                           # K23.7 K27.7 K29.7 K30.7


def disp(bits):
    return bits.count('1') - bits.count('0')


def encode(byte, k, rd):
    """-> (10-bit string abcdeifghj, new rd).  rd: -1 or +1."""
    x, y = byte & 31, byte >> 5
    if k:
        if byte not in K_CODES:
            raise ValueError(f'K.{x}.{y} is not a valid control code')
        six = K28_6[0 if rd < 0 else 1] if x == 28 else D6[x][0 if rd < 0 else 1]
    else:
        six = D6[x][0 if rd < 0 else 1]
    rd6 = rd if disp(six) == 0 else (1 if disp(six) > 0 else -1)
    if k and x == 28:
        # K28.y keeps the comma: the fghj is the RD+ column when the 6b left
        # RD positive, its complement otherwise (K28.7 uses the alternate)
        base = A7[1] if y == 7 else D4[y][1]
        four = base if rd6 > 0 else ''.join('1' if c == '0' else '0' for c in base)
    elif y == 7 and (k or (rd6 < 0 and x in (17, 18, 20)) or (rd6 > 0 and x in (11, 13, 14))):
        four = A7[0 if rd6 < 0 else 1]
    else:
        four = D4[y][0 if rd6 < 0 else 1]
    rd10 = rd6 if disp(four) == 0 else (1 if disp(four) > 0 else -1)
    return six + four, rd10


def all_codes():
    for rd in (-1, 1):
        for b in range(256):
            yield b, False, rd, *encode(b, False, rd)
        for b in sorted(K_CODES):
            yield b, True, rd, *encode(b, True, rd)


def self_check():
    seen = {}
    for b, k, rd, code, nrd in all_codes():
        d = disp(code)
        assert d in (0, 2, -2), (b, k, rd, code)
        assert d == 0 or (d > 0) == (rd < 0), f'disparity sign wrong for {b:02x} k={k} rd={rd}: {code}'
        assert '111111' not in code and '000000' not in code, (b, k, code)
        comma = '0011111' in code or '1100000' in code
        assert comma == (k and b in (0x3C, 0xBC, 0xFC)), f'comma in {b:02x} k={k}: {code}'
        key = int(code, 2)
        assert key not in seen or seen[key][:2] == (b, k), f'{code} decodes two ways'
        seen[key] = (b, k, rd)
    # spot values every 8b/10b reference quotes
    assert encode(0xBC, True, -1)[0] == '0011111010'    # K28.5 RD-
    assert encode(0xBC, True, 1)[0] == '1100000101'     # K28.5 RD+
    assert encode(0x50, False, 1)[0] == '1001000101'    # D16.2 RD+ (the /I2/ idle's second byte)
    assert encode(0xB5, False, -1)[0] == '1010101010'   # D21.5
    return seen


def write_verilog(seen):
    enc = ['// generated by gen_8b10b.py - do not edit',
           'module enc8b10b(input [7:0] d, input k, input rd_in, output reg [9:0] q, output reg rd_out);',
           '  // rd_in / rd_out: 0 = RD-, 1 = RD+.  q[9] = a, sent first.',
           '  always @* begin',
           '    case ({rd_in, k, d})']
    for rd in (-1, 1):
        for b in range(256):
            code, nrd = encode(b, False, rd)
            enc.append(f"      10'b{1 if rd > 0 else 0}0{b:08b}: begin q = 10'b{code}; rd_out = 1'b{1 if nrd > 0 else 0}; end")
        for b in sorted(K_CODES):
            code, nrd = encode(b, True, rd)
            enc.append(f"      10'b{1 if rd > 0 else 0}1{b:08b}: begin q = 10'b{code}; rd_out = 1'b{1 if nrd > 0 else 0}; end")
    enc += ["      default: begin q = 10'b0011111010; rd_out = 1'b1; end   // invalid K: K28.5",
            '    endcase', '  end', 'endmodule', '']
    open(os.path.join(HERE, 'enc8b10b.v'), 'w').write('\n'.join(enc))
    dec = ['// generated by gen_8b10b.py - do not edit',
           'module dec8b10b(input [9:0] q, output reg [7:0] d, output reg k, output reg err,',
           '                output reg rd_neutral, output reg rd_pos);',
           '  // err = not a valid code in either disparity; rd_pos = the code ends RD+',
           '  // (only meaningful when rd_neutral = 0)',
           '  always @* begin',
           "    d = 8'h00; k = 1'b0; err = 1'b0; rd_neutral = 1'b0; rd_pos = 1'b0;",
           '    case (q)']
    for key in sorted(seen):
        b, k, rd = seen[key]
        code = f'{key:010b}'
        dd = disp(code)
        enc_rd = 'rd_neutral = 1\'b1;' if dd == 0 else f"rd_pos = 1'b{1 if dd > 0 else 0};"
        dec.append(f"      10'b{code}: begin d = 8'h{b:02x}; k = 1'b{1 if k else 0}; {enc_rd} end")
    dec += ["      default: err = 1'b1;", '    endcase', '  end', 'endmodule', '']
    open(os.path.join(HERE, 'dec8b10b.v'), 'w').write('\n'.join(dec))
    # vectors for the Verilog testbench: rd k d code
    with open(os.path.join(HERE, 'vectors_8b10b.txt'), 'w') as f:
        for b, k, rd, code, nrd in all_codes():
            f.write(f"{1 if rd > 0 else 0} {1 if k else 0} {b:02x} {int(code, 2):03x} {1 if nrd > 0 else 0}\n")


if __name__ == '__main__':
    table = self_check()
    write_verilog(table)
    print(f'8b/10b: {len(table)} distinct codes, self-check passed; enc8b10b.v dec8b10b.v written')
